### ISSUE TITLE
Cross-reference platform version's repos

### ISSUE THREAD

**Issue by ablekh** [Imperssonator/GTFiber-Windows#1]
I would suggest to update README of each platform version's repo to include reference(s) to alternative platform version's repo(s). That way there will be no need to include all relevant links and info on MATIN's Materials Informatics Tools page, which is redundant.

**Comment by Imperssonator** [comment]
Cross references have been added to both the READMEs of GTFiber-Mac and GTFiber-Windows. Thanks for bringing that to my attention.

**Comment by ablekh** [comment]
@Imperssonator My pleasure.
